#!/bin/bash

# Define the path to the Python script
PYTHON_SCRIPT="/home/emmanuel/alx-higher_level_programming/0x00-python-hello_world/main.py"

# Run the Python script using Python
python3 "$PYTHON_SCRIPT"
